### ISSUE TITLE
ubuntu 18 build problem

### ISSUE THREAD

**Issue by levan89** [ojacoin/ojxcoin#5]
levan89@ubuntu:~$ cd /usr/src
levan89@ubuntu:/usr/src$ cd ojx/
levan89@ubuntu:/usr/src/ojx$ ./autogen.sh
./autogen.sh: 9: ./autogen.sh: autoreconf: not found

**Comment by ojacoin** [comment]
sudo apt-get install autoconf

**Comment by levan89** [comment]
thanks
