### ISSUE TITLE
bad practice to put IP Addresses for Seed address, should be DNS addresses

### ISSUE THREAD

**Issue by boy-m** [ojacoin/ojxcoin#6]
https://github.com/ojacoin/ojxcoin/blob/a9b9e1fd431dfe53a4d562e4dd9435e9698f3719/src/chainparams.cpp#L184

This is not a good practice. You should not add IP addresses for seed. you should add DNS , for example:
seed1.ojacoin.org
seed2.ojacoin.org
seed3.ojacoin.org
...
...
seed10.ojacoin.org

This way if they node done, you can just change the IP address in the DNS configuration outside of the wallet. and you will not need to ask everyone to update the wallet to change seed address.

**Comment by ojacoin** [comment]
While as you said using DNS instead of plain IP, is a better way to add seed nodes. It is not mandatory to do it, and if the seed node IP's change, we can just update the source and recompile it with the new IP's.

**Comment by boy-m** [comment]
I didn't say it was mandatory. I said it was a bad practice.
and if you recompile source code, it will be hard to ask people who run MNs to update immediately.
